### ISSUE TITLE
Flat-distributor: cancelling airdrop

### ISSUE THREAD

**Issue by k666-bit** [praskoson/distribution-tools#18]
Hi, it seems that I'm not able to perform the airdrop with flat-distributor, I've double checked everything and the env is correct, mint address, solana address etc.

The error I'm getting is:

```
Running the airdrop in non-interactive mode. The airdrop will run without additional confirmations.
--------------------------------------------------
Enter Y to proceed
> y
Log file handlers closed.
Cancelling the airdrop.
```

this happens instantly and quits. Nothing in the logs

**Comment by RickardVMiun** [comment]
Same here. Did you figure it out?

**Comment by k666-bit** [comment]
> Same here. Did you figure it out?

Just type in Y upper-case instead of lower-case y. Stupid I know, but that's it!
